### ISSUE TITLE
所有玩家绑定均显示在云黑 查云黑玩家和反馈结果对不上

### ISSUE THREAD

**Issue by xnhjs233** [XingShuyu/X-Robot#2]
![image](https://github.com/XingShuyu/X-Robot/assets/111108745/2ad50e95-6d00-4e83-9abe-43c9cdd4e349)
![image](https://github.com/XingShuyu/X-Robot/assets/111108745/b6225298-0f49-4e53-a086-a8c4baf0fd5c)

**Comment by XingShuyu** [comment]
云黑的问题，现已解决
